version: '{build}'

clone_depth: 10

matrix:
  fast_finish: true

environment:
  matrix:
    - VisualStudioVersion: 12.0
      platform: Win32
      configuration: Debug
      vcvarsall_platform: x86
      PlatformToolset: v120
    - VisualStudioVersion: 12.0
      platform: Win32
      configuration: Release
      vcvarsall_platform: x86
      PlatformToolset: v120
      MYQTDIR: C:\Qt\5.6\msvc2013
    - VisualStudioVersion: 12.0
      platform: x64
      configuration: Debug
      vcvarsall_platform: x64
      PlatformToolset: v120
    - VisualStudioVersion: 12.0
      platform: x64
      configuration: Release
      vcvarsall_platform: x64
      PlatformToolset: v120
      MYQTDIR: C:\Qt\5.6\msvc2013_64
#    - VisualStudioVersion: 14.0
#      platform: Win32
#      configuration: Debug
#      vcvarsall_platform: x86
#      PlatformToolset: v140
#    - VisualStudioVersion: 14.0
#      platform: Win32
#      configuration: Release
#      vcvarsall_platform: x86
#      PlatformToolset: v140
#      MYQTDIR: C:\Qt\5.11\msvc2015
#    - VisualStudioVersion: 14.0
#      platform: x64
#      configuration: Debug
#      vcvarsall_platform: x64
#      PlatformToolset: v140
# That platform causes frequent errors on appveyor due to an unknown infrastructure failure
#    - VisualStudioVersion: 14.0
#      platform: x64
#      configuration: Release
#      vcvarsall_platform: x64
#      PlatformToolset: v140
#      MYQTDIR: C:\Qt\5.11\msvc2015_64
    - VisualStudioVersion: 15.0
      platform: x64
      configuration: Release
      vcvarsall_platform: x64
      PlatformToolset: v141
      MYQTDIR: C:\Qt\5.12.2\msvc2017_64

install:
  - pip install pytest

build_script:
  - ECHO Building %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  # cmake..
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=OFF -G"NMake Makefiles" ..
  - nmake
  - copy bin\cppcheck.exe ..
  - cd ..
  # build gui..
  - ECHO MYQTDIR=%MYQTDIR%
  - 'IF defined MYQTDIR cd gui'
  - 'IF defined MYQTDIR set QTDIR=%MYQTDIR%'
  - 'IF defined MYQTDIR %QTDIR%\bin\qmake'
  - 'IF defined MYQTDIR nmake'
  - 'IF defined MYQTDIR cd ..'

test_script:
  #- build\bin\testrunner.exe -q
#  - IF EXIST bin\debug\testrunner.exe bin\debug\testrunner.exe
#  - IF EXIST bin\testrunner.exe bin\testrunner.exe
  - cd test\cli
  - python -m pytest test-helloworld.py
  - python -m pytest test-inline-suppress.py
  - python -m pytest test-suppress-syntaxError.py

artifacts:
  - path: bin
    name: CLI binaries
    type: zip
  - path: Build\gui
    name: GUI binaries
    type: zip
